# Generated by Django 4.1.6 on 2023-02-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_guardian_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='password',
        ),
    ]
